### ISSUE TITLE
Blog author text is not rendering as links

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5314] opened 2022-05-03 10:05 UTC
Nick Moore reported that Blog author text is not currently rendering as links. The frontmatter allows for "author" and "authorUrl" but in at least the two posts linked, and probably more, the author titles don't end up being clickable. Is this a bug or are we inputting "authorUrl" incorrectly?

Blogpost with multiple authors should be accommodated as well with separate links for each other.

**Error example:**
`/blog/real-weakest-link-in-software-supply-chain-security/`
![image](https://user-images.githubusercontent.com/59381432/169609114-2ba25f90-a022-4e5f-9896-d15dc40bb0a2.png)
`/blog/remote-software-development-made-easier/`
![image](https://user-images.githubusercontent.com/59381432/169609141-c152e560-e78a-4b11-baab-9a315ad9dbb9.png)

Relevant links: Asana card(s), Github issues, reference links, RFCs, docs, etc.
https://github.com/sourcegraph/about/pull/5303
https://github.com/sourcegraph/about/blob/main/blogposts/2022/introducting-migrator-service.md + https://about.sourcegraph.com/blog/introducing-migrator-service/

**Comment by bretthayes** [comment] 2022-05-20 20:42
Looks like #5328 is a dupe of this @st0nebraker

**Comment by st0nebraker** [comment] 2022-05-20 20:52
They're slightly different but we can merge them because this issue was fixed in [PR#5323](https://github.com/sourcegraph/about/pull/5324) but not ported over to the `replatform` so the fix is lost. The multiple author links fix I had needs re-working since the replatform re-architected the blog posts

**Closed** 2022-05-31 18:48 UTC
Labels: bug, about-blog, team/content-platform, sprint-rollover
