### ISSUE TITLE
Re-design out-dated Case Study pages

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/about#5422] opened 2022-06-02 23:19 UTC
The following pages should be refactored into our newest [Case Study layout design](https://www.figma.com/file/zfUyNxFFRDS713lIl3UZMa/Nutanix-landing-page?node-id=0%3A1):

- [FactSet case study](https://about.sourcegraph.com/case-studies/factset-migrates-from-perforce-to-github) - `/case-studies/factset-migrates-from-perforce-to-github`
- [Cloudfare case study](https://about.sourcegraph.com/case-studies/cloudflare-accelerates-debugging-and-improves-security) - `/case-studies/cloudflare-accelerates-debugging-and-improves-security`
- [Indeed case study](https://about.sourcegraph.com/case-studies/indeed-accelerates-development-velocity) - `/case-studies/indeed-accelerates-development-velocity`
- [Workiva case study](https://about.sourcegraph.com/case-studies/workiva-automates-large-scale-code-changes) - `/case-studies/workiva-automates-large-scale-code-changes`
- [CERN case study](https://about.sourcegraph.com/case-studies/cern-reduces-technical-debt) - `/case-studies/cern-reduces-technical-debt`
- [Criteo case study](https://about.sourcegraph.com/case-studies/criteo-tackles-big-code) - `/case-studies/criteo-tackles-big-code`
- [f5 case study](https://about.sourcegraph.com/case-studies/f5-streamlines-collaboration-globally) - `/case-studies/f5-streamlines-collaboration-globally`
- [Convoy case study](https://about.sourcegraph.com/case-studies/convoy-improved-on-boarding) - `/case-studies/convoy-improved-on-boarding`
- [Lyft case study](https://about.sourcegraph.com/case-studies/lyft-monolith-to-microservices) - `/case-studies/lyft-monolith-to-microservices`
- [Quantcast case study](https://about.sourcegraph.com/case-studies/quantcast-large-scale-refactoring) - `/case-studies/quantcast-large-scale-refactoring`
- [SoFi case study](https://about.sourcegraph.com/case-studies/sofi-moves-fast-on-hundreds-of-microservices) - `/case-studies/sofi-moves-fast-on-hundreds-of-microservices`
- [THORN case study](https://about.sourcegraph.com/case-studies/we-are-thorn) - `/case-studies/we-are-thorn`

This issue anticipates making layout changes to these pages to ensure consistency across the Case Study pages.

1. Brand should first re-design these pages to conform them to our newest design: [here](https://www.figma.com/file/zfUyNxFFRDS713lIl3UZMa/Nutanix-landing-page).
2. Then developers should implement, removing the current `CaseStudyLayout.tsx` in favor of `NewCaseStudyLayout.tsx`. The new layout can keep the old naming once all layouts are standardized.

**Comment by bretthayes** [comment] 2022-10-17 18:25
Dupe of #5421

**Closed by bretthayes** 2022-10-17 18:25 UTC
Labels: design refresh, team/content-platform
